### ISSUE TITLE
Erro inicializando Transcription Client

### ISSUE THREAD

**Issue by ericrib** [CPqD/trd-sdk-python#2]
Olá,

Trabalho na Hvar e estava fazendo alguns testes com o SDK e queria uma ajuda se possível.
Estou iniciando o `Transcription Client` conforme indicado no README
```
cpqd_client = TranscriptionClient(
    api_url="https://speech.cpqd.com.br/trd/v3",
    webhook_port=8443, # Outbound, precisa de redirecionamento para a WAN
    webhook_host="100.100.100.100", # IP externo ou DNS
    webhook_listener='0.0.0.0',
    webhook_protocol="https",
    username=cpqd_username,
    password=cpqd_password
    )
```
Mas recebo "reachable":false do request de validação do webhook e o erro
`ConnectionError: 100.100.100.100:8443 not reachable by the transcription server` .

Consigo fazer a requisição por curl com a senha e usuário providenciados sem problemas.
Vocês tem alguma ideia de como contornar esse erro?

Desde já, agradeço.
Att.
Eric Ribeiro

**Comment by gustavocuozzo** [comment]
> Olá,
> 
> Trabalho na Hvar e estava fazendo alguns testes com o SDK e queria uma ajuda se possível.
> Estou iniciando o `Transcription Client` conforme indicado no README
> 
> ```
> cpqd_client = TranscriptionClient(
>     api_url="https://speech.cpqd.com.br/trd/v3",
>     webhook_port=8443, # Outbound, precisa de redirecionamento para a WAN
>     webhook_host="100.100.100.100", # IP externo ou DNS
>     webhook_listener='0.0.0.0',
>     webhook_protocol="https",
>     username=cpqd_username,
>     password=cpqd_password
>     )
> ```
> 
> Mas recebo "reachable":false do request de validação do webhook e o erro
> `ConnectionError: 100.100.100.100:8443 not reachable by the transcription server` .
> 
> Consigo fazer a requisição por curl com a senha e usuário providenciados sem problemas.
> Vocês tem alguma ideia de como contornar esse erro?
> 
> Desde já, agradeço.
> Att.
> Eric Ribeiro

Olá Eric, no **webhook_host** utilize seu IP público. Se sua rede tiver firewall/roteador, precisará fazer um redirecionamento da porta definida em **webhook_port**.

**Comment by ericrib** [comment]
Obrigado

Funcionou na minha máquina local porém ainda estão sendo feitos ajustes para rodar em nuvem.
